### ISSUE TITLE
Database Error (SOLVED)

### ISSUE THREAD

**Issue by asimanstudios** [Vallerian/MelodyMine#37]
I have closely followed the Linux installation provided in the wiki documentation and I get a crash error which tells me something about the melodymine table not being found, I attach the error:

PrismaClientKnownRequestError:
Invalid `prisma.melodymine.updateMany()` invocation in
/MelodyMine/web/server/server.ts:478:29

  475
  476 server.listen(PORT, async () => {
  477     console.log(`Server listening on port ${PORT}.`)
→ 478     await prisma.melodymine.updateMany(
The table `melodymine` does not exist in the current database.
    at Cn.handleRequestError (/MelodyMine/web/server/node_modules/@prisma/client/runtime/library.js:123:6817)
    at Cn.handleAndLogRequestError (/MelodyMine/web/server/node_modules/@prisma/client/runtime/library.js:123:6206)
    at Cn.request (/MelodyMine/web/server/node_modules/@prisma/client/runtime/library.js:123:5926)
    at async l (/MelodyMine/web/server/node_modules/@prisma/client/runtime/library.js:128:9968) {
  code: 'P2021',
  clientVersion: '5.4.2',
  meta: { table: 'melodymine' }
}
[nodemon] app crashed - waiting for file changes before starting...

**
I would be very grateful if someone could provide me with a solution, greetings.**

**Comment by Vallerian** [comment]
you must first install plugin in your server that make `melodymine` table

**Comment by asimanstudios** [comment]
IEl plugin ya lo tengo instalado dentro del servidor, he realizado reinicios y aun asi no consigo que se genere, dentro del servidor me da este error:


[00:53:13 WARN]: ir.taher7.melodymine.kotlin.UninitializedPropertyAccessException: lateinit property hikari has not been initialized
[00:53:13 WARN]:        at MelodyMine-1.5.0 (1).jar//ir.taher7.melodymine.database.Database.getHikari(Database.kt:20)
[00:53:13 WARN]:        at MelodyMine-1.5.0 (1).jar//ir.taher7.melodymine.database.Database.createConnection(Database.kt:54)
[00:53:13 WARN]:        at MelodyMine-1.5.0 (1).jar//ir.taher7.melodymine.database.Database.access$createConnection(Database.kt:17)
[00:53:13 WARN]:        at MelodyMine-1.5.0 (1).jar//ir.taher7.melodymine.database.Database$findPlayer$1.run(Database.kt:117)
[00:53:13 WARN]:        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101)
[00:53:13 WARN]:        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[00:53:13 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[00:53:13 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[00:53:13 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[00:53:13 WARN]:        at java.base/java.lang.Thread.run(Thread.java:840)

**Comment by Vallerian** [comment]
What is your server version ?

**Comment by Vallerian** [comment]
you have to first config your database
![image](https://github.com/Vallerian/MelodyMine/assets/76476837/1620d6c6-5cfd-4282-aa0b-a0acb2d9f9d2)
