### ISSUE TITLE
Export encountered errors on following paths:   [The Client]

### ISSUE THREAD

**Issue by WavaDev** [Vallerian/MelodyMine#55]
```
> melody_client@1.5.4 build
> next build

 ✓ Creating an optimized production build    
 ✓ Compiled successfully

./src/components/HomeStart.tsx
20:8  Warning: React Hook useLayoutEffect has missing dependencies: 'route', 'setError', and 'setValidate'. Either include them or remove the dependency array.  react-hooks/exhaustive-deps

./src/components/LoginForm.tsx
60:8  Warning: React Hook useLayoutEffect has missing dependencies: 'route' and 'setError'. Either include them or remove the dependency array.  react-hooks/exhaustive-deps

./src/components/Porgress/ErrorBox.tsx
20:8  Warning: React Hook useEffect has a missing dependency: 'setErrorBox'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps

./src/components/SingleUser.tsx
431:12  Warning: React Hook useEffect has missing dependencies: 'onAcceptCallSelfPluginReceive', 'onAcceptCallTargetPluginReceive', 'onAdminModeDisableReceive', 'onAdminModeEnableReceive', 'onDenyCallSelfPluginReceive', 'onDenyCallTargetPluginReceive', 'onDisableVoiceReceive', 'onEnableVoiceReceive', 'onEndCallSelfPluginReceive', 'onEndCallTargetPluginReceive', 'onNewPlayerLeave', 'onPendingCallEndSelfPluginReceive', 'onPendingCallEndTargetPluginReceive', 'onPlayerChangeServer', 'onPlayerInitAdminModeReceive', 'onPlayerLeaveReceivePlugin', 'onReceiveAnswer', 'onReceiveCandidate', 'onReceiveOffer', 'onSetVolumeReceive', 'onStartCallSelfPluginReceive', and 'onStartCallTargetPluginReceive'. Either include them or remove the dependency array.  react-hooks/exhaustive-deps
438:8  Warning: React Hook useEffect has a missing dependency: 'closeRTC'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps
450:12  Warning: React Hook useEffect has missing dependencies: 'onPlayerChangeControlReceive' and 'onSetControlPluginReceive'. Either include them or remove the dependency array.  react-hooks/exhaustive-deps
460:8  Warning: React Hook useEffect has missing dependencies: 'stream' and 'uuid'. Either include them or remove the dependency array.  react-hooks/exhaustive-deps
544:8  Warning: React Hook useEffect has a missing dependency: 'user.uuid'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps
551:8  Warning: React Hook useEffect has a missing dependency: 'user.uuid'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps
565:8  Warning: React Hook useEffect has a missing dependency: 'checkPlayerCanTalk'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps

./src/components/SoundControl.tsx
87:8  Warning: React Hook useEffect has a missing dependency: 'onSetControlPluginReceive'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps

./src/components/StartButton.tsx
96:8  Warning: React Hook useLayoutEffect has missing dependencies: 'addIceServer', 'closeStream', 'disconnectSocket', 'removeAllOnline', 'route', 'setAdminModeAll', 'setSocket', and 'setValidate'. Either include them or remove the dependency array.  react-hooks/exhaustive-deps

./src/components/UserHead.tsx
81:8  Warning: React Hook useEffect has missing dependencies: 'isSelfMute', 'isTalk', 'socket', 'user.server', and 'user.uuid'. Either include them or remove the dependency array.  react-hooks/exhaustive-deps

./src/components/UserInfo.tsx
85:8  Warning: React Hook useEffect has missing dependencies: 'initSounds', 'setSecretKey', and 'websocketKey'. Either include them or remove the dependency array.  react-hooks/exhaustive-deps
104:8  Warning: React Hook useEffect has missing dependencies: 'onAdminModeDisableReceive', 'onAdminModeEnableReceive', 'onPauseSoundReceive', 'onPlaySoundReceive', 'onSoundSettingReceive', and 'onStopSoundReceive'. Either include them or remove the dependency array.  react-hooks/exhaustive-deps

./src/components/UserList.tsx
145:8  Warning: React Hook useEffect has missing dependencies: 'onNewPlayerLeave', 'onPlayerChangeServer', 'onPlayerJoinReceive', 'onPlayerLeaveReceivePlugin', 'onPlayerMuteReceive', 'onPlayerStartVoiceReceive', 'onPlayerUnmuteReceive', and 'onPluginDisabled'. Either include them or remove the dependency array.  react-hooks/exhaustive-deps

./src/config.ts
1:1  Warning: Assign object to a variable before exporting as module default  import/no-anonymous-default-export

./src/errorMessages.ts
1:1  Warning: Assign array to a variable before exporting as module default  import/no-anonymous-default-export

./src/sounds.ts
1:1  Warning: Assign array to a variable before exporting as module default  import/no-anonymous-default-export

info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules
 ✓ Linting and checking validity of types    
 ✓ Collecting page data    
   Generating static pages (0/8)  [=   ]TypeError [ERR_INVALID_URL]: Invalid URL
    at new NodeError (node:internal/errors:405:5)
    at new URL (node:internal/url:611:13)
    at t.default (/root/MelodyMine/web/client/.next/server/chunks/417.js:1:22142)
    at 74284 (/root/MelodyMine/web/client/.next/server/chunks/417.js:1:15077)
    at __webpack_require__ (/root/MelodyMine/web/client/.next/server/webpack-runtime.js:1:161)
    at 41978 (/root/MelodyMine/web/client/.next/server/chunks/163.js:1:638)
    at __webpack_require__ (/root/MelodyMine/web/client/.next/server/webpack-runtime.js:1:161)
    at A (/root/MelodyMine/web/client/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:35:5655)
    at R (/root/MelodyMine/web/client/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:35:4334)
    at rh (/root/MelodyMine/web/client/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:27:25718) {
  input: "https://voice.skolon.lol          # Your website's URL. 🌐",
  code: 'ERR_INVALID_URL'
}

Error occurred prerendering page "/_not-found". Read more: https://nextjs.org/docs/messages/prerender-error
TypeError [ERR_INVALID_URL]: Invalid URL
    at new NodeError (node:internal/errors:405:5)
    at new URL (node:internal/url:611:13)
    at t.default (/root/MelodyMine/web/client/.next/server/chunks/417.js:1:22142)
    at 74284 (/root/MelodyMine/web/client/.next/server/chunks/417.js:1:15077)
    at __webpack_require__ (/root/MelodyMine/web/client/.next/server/webpack-runtime.js:1:161)
    at 41978 (/root/MelodyMine/web/client/.next/server/chunks/163.js:1:638)
    at __webpack_require__ (/root/MelodyMine/web/client/.next/server/webpack-runtime.js:1:161)
    at A (/root/MelodyMine/web/client/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:35:5655)
    at R (/root/MelodyMine/web/client/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:35:4334)
    at rh (/root/MelodyMine/web/client/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:27:25718)
   Generating static pages (5/8)  [==  ] 
TypeError [ERR_INVALID_URL]: Invalid URL
    at new NodeError (node:internal/errors:405:5)
    at new URL (node:internal/url:611:13)
    at t.default (/root/MelodyMine/web/client/.next/server/chunks/417.js:1:22142)
    at 74284 (/root/MelodyMine/web/client/.next/server/chunks/417.js:1:15077)
    at __webpack_require__ (/root/MelodyMine/web/client/.next/server/webpack-runtime.js:1:161)
    at 41978 (/root/MelodyMine/web/client/.next/server/chunks/163.js:1:638)
    at __webpack_require__ (/root/MelodyMine/web/client/.next/server/webpack-runtime.js:1:161)
    at A (/root/MelodyMine/web/client/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:35:5655)
    at R (/root/MelodyMine/web/client/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:35:4334)
    at rh (/root/MelodyMine/web/client/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:27:25718) {
  input: "https://voice.skolon.lol          # Your website's URL. 🌐",
  code: 'ERR_INVALID_URL'
}

Error occurred prerendering page "/hub". Read more: https://nextjs.org/docs/messages/prerender-error
TypeError [ERR_INVALID_URL]: Invalid URL
    at new NodeError (node:internal/errors:405:5)
    at new URL (node:internal/url:611:13)
    at t.default (/root/MelodyMine/web/client/.next/server/chunks/417.js:1:22142)
    at 74284 (/root/MelodyMine/web/client/.next/server/chunks/417.js:1:15077)
    at __webpack_require__ (/root/MelodyMine/web/client/.next/server/webpack-runtime.js:1:161)
    at 41978 (/root/MelodyMine/web/client/.next/server/chunks/163.js:1:638)
    at __webpack_require__ (/root/MelodyMine/web/client/.next/server/webpack-runtime.js:1:161)
    at A (/root/MelodyMine/web/client/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:35:5655)
    at R (/root/MelodyMine/web/client/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:35:4334)
    at rh (/root/MelodyMine/web/client/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:27:25718)
TypeError [ERR_INVALID_URL]: Invalid URL
    at new NodeError (node:internal/errors:405:5)
    at new URL (node:internal/url:611:13)
    at t.default (/root/MelodyMine/web/client/.next/server/chunks/417.js:1:22142)
    at 74284 (/root/MelodyMine/web/client/.next/server/chunks/417.js:1:15077)
    at __webpack_require__ (/root/MelodyMine/web/client/.next/server/webpack-runtime.js:1:161)
    at 41978 (/root/MelodyMine/web/client/.next/server/chunks/163.js:1:638)
    at __webpack_require__ (/root/MelodyMine/web/client/.next/server/webpack-runtime.js:1:161)
    at A (/root/MelodyMine/web/client/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:35:5655)
    at R (/root/MelodyMine/web/client/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:35:4334)
    at rh (/root/MelodyMine/web/client/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:27:25718) {
  input: "https://voice.skolon.lol          # Your website's URL. 🌐",
  code: 'ERR_INVALID_URL'
}

Error occurred prerendering page "/login". Read more: https://nextjs.org/docs/messages/prerender-error
TypeError [ERR_INVALID_URL]: Invalid URL
    at new NodeError (node:internal/errors:405:5)
    at new URL (node:internal/url:611:13)
    at t.default (/root/MelodyMine/web/client/.next/server/chunks/417.js:1:22142)
    at 74284 (/root/MelodyMine/web/client/.next/server/chunks/417.js:1:15077)
    at __webpack_require__ (/root/MelodyMine/web/client/.next/server/webpack-runtime.js:1:161)
    at 41978 (/root/MelodyMine/web/client/.next/server/chunks/163.js:1:638)
    at __webpack_require__ (/root/MelodyMine/web/client/.next/server/webpack-runtime.js:1:161)
    at A (/root/MelodyMine/web/client/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:35:5655)
    at R (/root/MelodyMine/web/client/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:35:4334)
    at rh (/root/MelodyMine/web/client/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:27:25718)
TypeError [ERR_INVALID_URL]: Invalid URL
    at new NodeError (node:internal/errors:405:5)
    at new URL (node:internal/url:611:13)
    at t.default (/root/MelodyMine/web/client/.next/server/chunks/417.js:1:22142)
    at 74284 (/root/MelodyMine/web/client/.next/server/chunks/417.js:1:15077)
    at __webpack_require__ (/root/MelodyMine/web/client/.next/server/webpack-runtime.js:1:161)
    at 41978 (/root/MelodyMine/web/client/.next/server/chunks/163.js:1:638)
    at __webpack_require__ (/root/MelodyMine/web/client/.next/server/webpack-runtime.js:1:161)
    at A (/root/MelodyMine/web/client/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:35:5655)
    at R (/root/MelodyMine/web/client/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:35:4334)
    at rh (/root/MelodyMine/web/client/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:27:25718) {
  input: "https://voice.skolon.lol          # Your website's URL. 🌐",
  code: 'ERR_INVALID_URL'
}

Error occurred prerendering page "/". Read more: https://nextjs.org/docs/messages/prerender-error
TypeError [ERR_INVALID_URL]: Invalid URL
    at new NodeError (node:internal/errors:405:5)
    at new URL (node:internal/url:611:13)
    at t.default (/root/MelodyMine/web/client/.next/server/chunks/417.js:1:22142)
    at 74284 (/root/MelodyMine/web/client/.next/server/chunks/417.js:1:15077)
    at __webpack_require__ (/root/MelodyMine/web/client/.next/server/webpack-runtime.js:1:161)
    at 41978 (/root/MelodyMine/web/client/.next/server/chunks/163.js:1:638)
    at __webpack_require__ (/root/MelodyMine/web/client/.next/server/webpack-runtime.js:1:161)
    at A (/root/MelodyMine/web/client/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:35:5655)
    at R (/root/MelodyMine/web/client/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:35:4334)
 ✓ Generating static pages (8/8) 

> Export encountered errors on following paths:
        /_not-found
        /hub/page: /hub
        /login/page: /login
        /page: /
```

**Comment by WavaDev** [comment]
Fixed it, changed all files that has pages.tsx to index.tsx
